---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  require_chef_omnibus: 12.21.1

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      linked_clone: true
  - name: ubuntu-14.04
    driver:
      linked_clone: true

suites:
  - name: default
    run_list:
      - recipe[iamdefn::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
