name 'meh'
description 'Installs/Configures meh'
long_description 'Installs/Configures meh'
maintainer 'defn ghiem'
maintainer_email 'iam@defn.sh'
license 'Apache-2.0'
version '0.1.0'
chef_version '>= 12.1' if respond_to?(:chef_version)
issues_url 'https://github.com/imma/defn/issues'
source_url 'https://github.com/imma/defn'
supports 'ubuntu'
depends 'iamdefn'
