#!/usr/bin/env bash

function ptt {
  export nm_user="${USER:-${LOGNAME}}"
  local tmp_pt="$(mktemp -t XXXXXX)"
  proctree > "$tmp_pt"
  cat "$tmp_pt" | egrep -v ' /(Applications|System|usr/sbin|usr/libexec)' | grep " ${nm_user} " | perl -pe 's{ $ENV{"nm_user"}}{ }; s{^(.*?) (\d+) (.*)$}{$1 $3}' | cut -b1-$COLUMNS
  rm -f "$tmp_pt"
}

function _defn_profile {
  local shome="${_defn_home:="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  PATH="$shome/bin:$PATH"
}

_defn_profile
