#!/usr/bin/env bash

function pt {
  export nm_user="${USER:-${LOGNAME}}"
  proctree | egrep -v ' /(Applications|System|Library|usr)' | grep " ${nm_user} " | perl -pe 's{ $ENV{"nm_user"}}{ }; s{^(.*?) (\d+) (.*)$}{$1 $3}' | cut -b1-$COLUMNS
}
